version: "3"

services:
  hadoop:
    image: big-data-plataform:latest
    container_name: big-data-plataform
    restart: always
    ports:
      - 8088:8088 
      - 50070:50070
      - 9000:9000
      - 9092:9092
      - 8000:8000
    volumes:
      - ./scripts:/scripts
      - ./raw-data:/raw-data
      - ./app:/app
    env_file:
      - ./.env
    user: root



